// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AddEventEntry = {
    name: string;
    eventDateStart: string;
    description?: string | null;
    eventDateEnd?: string | null;
};

export type AddPurchaseEntry = {
    name: string;
    cost: number;
    participantId: string;
    purchaseUsages: Array<UpsertPurchaseUsageEntry>;
};

export type ApiError = {
    errorCode?: string | null;
    message?: string | null;
    messageTemplate?: string | null;
    args?: Array<unknown> | null;
    httpStatus?: number;
};

export type EventShortEntry = {
    id: string;
    name: string;
    description?: string | null;
    eventDateStart: string;
    eventDateEnd?: string | null;
    isCompleted: boolean;
    imageUri?: string | null;
};

export type EventShortEntryResponse = {
    data?: Array<EventShortEntry> | null;
    totalPages?: number;
    total?: number;
};

export type FileType = 'Jpg' | 'Jpeg' | 'Png' | 'Pdf' | 'Txt' | 'Doc' | 'Docx' | 'Xls' | 'Xlsx' | 'Link';

export type GetDebtEntry = {
    id?: string;
    amount?: number;
    isSent?: boolean;
    isComfirmed?: boolean;
    event?: EventShortEntry;
    lender?: UserShortEntry;
    debtor?: UserShortEntry;
};

export type GetDebtEntryResponse = {
    data?: Array<GetDebtEntry> | null;
    totalPages?: number;
    total?: number;
};

export type GetEventEntry = {
    id: string;
    name: string;
    description?: string | null;
    createdDate: string;
    eventDateStart: string;
    eventDateEnd?: string | null;
    isCompleted: boolean;
    mediaUri?: string | null;
    user: UserShortEntry;
    participants?: Array<ParticipantShortEntry> | null;
    purchases?: Array<PurchaseShortEntry> | null;
    medias?: Array<MediaShortEntry> | null;
};

export type GetMediaEntry = {
    id?: string;
    fileType?: FileType;
    fileName?: string | null;
    mediaType?: MediaType;
    link?: string | null;
    event?: EventShortEntry;
};

export type GetParticipantEntry = {
    id: string;
    user: GetUserEntry;
    event: EventShortEntry;
    purchases?: Array<PurchaseShortEntry> | null;
    purchaseUsages?: Array<PurchaseUsageShortEntry> | null;
};

export type GetPurchaseEntry = {
    id: string;
    name: string;
    cost: number;
    isComplete: boolean;
    eventId: string;
    purchaseUsages?: Array<PurchaseUsageShortEntry> | null;
    participant?: ParticipantShortEntry;
};

export type GetPurchaseEntryResponse = {
    data?: Array<GetPurchaseEntry> | null;
    totalPages?: number;
    total?: number;
};

export type GetUserEntry = {
    id?: string | null;
    name?: string | null;
    email?: string | null;
    role?: string | null;
    firstName?: string | null;
    middleName?: string | null;
    lastName?: string | null;
    phone?: string | null;
    imageUri?: string | null;
};

export type LoginModel = {
    username: string;
    password: string;
};

export type MediaShortEntry = {
    id?: string;
    fileType?: FileType;
    fileName?: string | null;
    mediaType?: MediaType;
    link?: string | null;
};

export type MediaType = 'Image' | 'Video' | 'Audio' | 'Document' | 'Link' | 'Unknown';

export type ParticipantShortEntry = {
    id: string;
    name?: string | null;
    imageUri?: string | null;
};

export type ParticipantShortEntryResponse = {
    data?: Array<ParticipantShortEntry> | null;
    totalPages?: number;
    total?: number;
};

export type PurchaseShortEntry = {
    id: string;
    eventId: string;
    name: string;
    cost: number;
    isComplete: boolean;
};

export type PurchaseUsageShortEntry = {
    purchaseUsageId: string;
    purchaseId?: string;
    participantId?: string;
    amount?: number;
};

export type RegisterModel = {
    username: string;
    email: string;
    password: string;
};

export type UpdateEventEntry = {
    name: string;
    description?: string | null;
    eventDateStart: string;
    eventDateEnd?: string | null;
};

export type UpdateModel = {
    username: string;
    firstName?: string | null;
    middleName?: string | null;
    lastName?: string | null;
    phone?: string | null;
};

export type UpdatePurchaseEntry = {
    name: string;
    cost: number;
    purchaseUsages: Array<UpsertPurchaseUsageEntry>;
};

export type UpsertParticipantEntry = {
    userId: string;
};

export type UpsertPurchaseUsageEntry = {
    participantId: string;
    amount: number;
};

export type UserShortEntry = {
    id?: string | null;
    name?: string | null;
    imageUri?: string | null;
};

export type PostApiV1AuthRegisterData = {
    /**
     * Модель для регистрации
     */
    body?: RegisterModel;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type PostApiV1AuthRegisterErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
};

export type PostApiV1AuthRegisterError = PostApiV1AuthRegisterErrors[keyof PostApiV1AuthRegisterErrors];

export type PostApiV1AuthRegisterResponses = {
    /**
     * Success
     */
    200: string;
};

export type PostApiV1AuthRegisterResponse = PostApiV1AuthRegisterResponses[keyof PostApiV1AuthRegisterResponses];

export type GetApiV1AuthEmailConfirmData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Логин пользователя
         */
        login?: string;
        /**
         * Код, отправленный на почту
         */
        code?: string;
    };
    url: '/api/v1/auth/email-confirm';
};

export type GetApiV1AuthEmailConfirmErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
};

export type GetApiV1AuthEmailConfirmError = GetApiV1AuthEmailConfirmErrors[keyof GetApiV1AuthEmailConfirmErrors];

export type PostApiV1AuthLoginData = {
    /**
     * Модель для логина
     */
    body?: LoginModel;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type PostApiV1AuthLoginErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
};

export type PostApiV1AuthLoginError = PostApiV1AuthLoginErrors[keyof PostApiV1AuthLoginErrors];

export type PostApiV1AuthLoginResponses = {
    /**
     * Success
     */
    200: string;
};

export type PostApiV1AuthLoginResponse = PostApiV1AuthLoginResponses[keyof PostApiV1AuthLoginResponses];

export type GetApiV1AuthAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/account';
};

export type GetApiV1AuthAccountErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
};

export type GetApiV1AuthAccountError = GetApiV1AuthAccountErrors[keyof GetApiV1AuthAccountErrors];

export type GetApiV1AuthAccountResponses = {
    /**
     * Success
     */
    200: GetUserEntry;
};

export type GetApiV1AuthAccountResponse = GetApiV1AuthAccountResponses[keyof GetApiV1AuthAccountResponses];

export type GetApiV1AuthUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Логин пользователя. Опциональное поле.
         */
        userName?: string;
    };
    url: '/api/v1/auth/users';
};

export type GetApiV1AuthUsersErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
};

export type GetApiV1AuthUsersError = GetApiV1AuthUsersErrors[keyof GetApiV1AuthUsersErrors];

export type GetApiV1AuthUsersResponses = {
    /**
     * Success
     */
    200: Array<UserShortEntry>;
};

export type GetApiV1AuthUsersResponse = GetApiV1AuthUsersResponses[keyof GetApiV1AuthUsersResponses];

export type PatchApiV1AuthEditData = {
    /**
     * Модель для обновления информации пользователя
     */
    body?: UpdateModel;
    path?: never;
    query?: never;
    url: '/api/v1/auth/edit';
};

export type PatchApiV1AuthEditErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
};

export type PatchApiV1AuthEditError = PatchApiV1AuthEditErrors[keyof PatchApiV1AuthEditErrors];

export type PatchApiV1AuthEditResponses = {
    /**
     * Success
     */
    200: GetUserEntry;
};

export type PatchApiV1AuthEditResponse = PatchApiV1AuthEditResponses[keyof PatchApiV1AuthEditResponses];

export type DeleteApiV1AuthAvatarData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/avatar';
};

export type DeleteApiV1AuthAvatarErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
};

export type DeleteApiV1AuthAvatarError = DeleteApiV1AuthAvatarErrors[keyof DeleteApiV1AuthAvatarErrors];

export type PostApiV1AuthAvatarData = {
    body?: {
        file?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/avatar';
};

export type PostApiV1AuthAvatarErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
};

export type PostApiV1AuthAvatarError = PostApiV1AuthAvatarErrors[keyof PostApiV1AuthAvatarErrors];

export type GetApiV1EventsByEventIdDebtsData = {
    body?: never;
    path: {
        /**
         * Id ивента (события)
         */
        eventId: string;
    };
    query?: {
        /**
         * Кол-во элементов которые необходимо пропустить
         */
        offset?: number;
        /**
         * Кол-во элементов на 1 странице
         */
        limit?: number;
    };
    url: '/api/v1/events/{eventId}/debts';
};

export type GetApiV1EventsByEventIdDebtsErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ApiError;
};

export type GetApiV1EventsByEventIdDebtsError = GetApiV1EventsByEventIdDebtsErrors[keyof GetApiV1EventsByEventIdDebtsErrors];

export type GetApiV1EventsByEventIdDebtsResponses = {
    /**
     * Success
     */
    200: GetDebtEntryResponse;
};

export type GetApiV1EventsByEventIdDebtsResponse = GetApiV1EventsByEventIdDebtsResponses[keyof GetApiV1EventsByEventIdDebtsResponses];

export type GetApiV1EventsByEventIdDebtsByDebtIdData = {
    body?: never;
    path: {
        /**
         * Id ивента (события)
         */
        eventId: string;
        debtId: string;
    };
    query?: never;
    url: '/api/v1/events/{eventId}/debts/{debtId}';
};

export type GetApiV1EventsByEventIdDebtsByDebtIdErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ApiError;
};

export type GetApiV1EventsByEventIdDebtsByDebtIdError = GetApiV1EventsByEventIdDebtsByDebtIdErrors[keyof GetApiV1EventsByEventIdDebtsByDebtIdErrors];

export type GetApiV1EventsByEventIdDebtsByDebtIdResponses = {
    /**
     * Success
     */
    200: GetDebtEntry;
};

export type GetApiV1EventsByEventIdDebtsByDebtIdResponse = GetApiV1EventsByEventIdDebtsByDebtIdResponses[keyof GetApiV1EventsByEventIdDebtsByDebtIdResponses];

export type PostApiV1EventsByEventIdDebtsByDebtIdSendData = {
    body?: never;
    path: {
        /**
         * Id ивента (события)
         */
        eventId: string;
        /**
         * Id пользователя - должника
         */
        debtId: string;
    };
    query?: never;
    url: '/api/v1/events/{eventId}/debts/{debtId}/send';
};

export type PostApiV1EventsByEventIdDebtsByDebtIdSendErrors = {
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ApiError;
};

export type PostApiV1EventsByEventIdDebtsByDebtIdSendError = PostApiV1EventsByEventIdDebtsByDebtIdSendErrors[keyof PostApiV1EventsByEventIdDebtsByDebtIdSendErrors];

export type PostApiV1EventsByEventIdDebtsByDebtIdSendResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiV1EventsByEventIdDebtsByDebtIdConfirmData = {
    body?: never;
    path: {
        /**
         * Id ивента (события)
         */
        eventId: string;
        /**
         * Id пользователя - должника
         */
        debtId: string;
    };
    query?: never;
    url: '/api/v1/events/{eventId}/debts/{debtId}/confirm';
};

export type PostApiV1EventsByEventIdDebtsByDebtIdConfirmErrors = {
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ApiError;
};

export type PostApiV1EventsByEventIdDebtsByDebtIdConfirmError = PostApiV1EventsByEventIdDebtsByDebtIdConfirmErrors[keyof PostApiV1EventsByEventIdDebtsByDebtIdConfirmErrors];

export type PostApiV1EventsByEventIdDebtsByDebtIdConfirmResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiV1EventsData = {
    body?: never;
    path?: never;
    query?: {
        offset?: number;
        limit?: number;
        name?: string;
        description?: string;
        createdDateStart?: string;
        createdDateEnd?: string;
        eventDateStartMin?: string;
        eventDateStartMax?: string;
        eventDateEndMin?: string;
        eventDateEndMax?: string;
        userId?: string;
        isCompleted?: boolean;
        isActive?: boolean;
        participantId?: string;
        purchaseId?: string;
    };
    url: '/api/v1/events';
};

export type GetApiV1EventsErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ApiError;
};

export type GetApiV1EventsError = GetApiV1EventsErrors[keyof GetApiV1EventsErrors];

export type GetApiV1EventsResponses = {
    /**
     * Success
     */
    200: EventShortEntryResponse;
};

export type GetApiV1EventsResponse = GetApiV1EventsResponses[keyof GetApiV1EventsResponses];

export type PostApiV1EventsData = {
    body?: AddEventEntry;
    path?: never;
    query?: never;
    url: '/api/v1/events';
};

export type PostApiV1EventsErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
};

export type PostApiV1EventsError = PostApiV1EventsErrors[keyof PostApiV1EventsErrors];

export type PostApiV1EventsResponses = {
    /**
     * Success
     */
    200: EventShortEntry;
};

export type PostApiV1EventsResponse = PostApiV1EventsResponses[keyof PostApiV1EventsResponses];

export type DeleteApiV1EventsByEventIdData = {
    body?: never;
    path: {
        eventId: string;
    };
    query?: never;
    url: '/api/v1/events/{eventId}';
};

export type DeleteApiV1EventsByEventIdErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
};

export type DeleteApiV1EventsByEventIdError = DeleteApiV1EventsByEventIdErrors[keyof DeleteApiV1EventsByEventIdErrors];

export type DeleteApiV1EventsByEventIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiV1EventsByEventIdData = {
    body?: never;
    path: {
        eventId: string;
    };
    query?: never;
    url: '/api/v1/events/{eventId}';
};

export type GetApiV1EventsByEventIdErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ApiError;
};

export type GetApiV1EventsByEventIdError = GetApiV1EventsByEventIdErrors[keyof GetApiV1EventsByEventIdErrors];

export type GetApiV1EventsByEventIdResponses = {
    /**
     * Success
     */
    200: GetEventEntry;
};

export type GetApiV1EventsByEventIdResponse = GetApiV1EventsByEventIdResponses[keyof GetApiV1EventsByEventIdResponses];

export type PatchApiV1EventsByEventIdData = {
    body?: UpdateEventEntry;
    path: {
        eventId: string;
    };
    query?: never;
    url: '/api/v1/events/{eventId}';
};

export type PatchApiV1EventsByEventIdErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
};

export type PatchApiV1EventsByEventIdError = PatchApiV1EventsByEventIdErrors[keyof PatchApiV1EventsByEventIdErrors];

export type PatchApiV1EventsByEventIdResponses = {
    /**
     * Success
     */
    200: EventShortEntry;
};

export type PatchApiV1EventsByEventIdResponse = PatchApiV1EventsByEventIdResponses[keyof PatchApiV1EventsByEventIdResponses];

export type DeleteApiV1EventsByEventIdPhotoData = {
    body?: never;
    path: {
        eventId: string;
    };
    query?: never;
    url: '/api/v1/events/{eventId}/photo';
};

export type DeleteApiV1EventsByEventIdPhotoErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type DeleteApiV1EventsByEventIdPhotoResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PatchApiV1EventsByEventIdPhotoData = {
    body?: {
        file?: Blob | File;
    };
    path: {
        eventId: string;
    };
    query?: never;
    url: '/api/v1/events/{eventId}/photo';
};

export type PatchApiV1EventsByEventIdPhotoErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
};

export type PatchApiV1EventsByEventIdPhotoError = PatchApiV1EventsByEventIdPhotoErrors[keyof PatchApiV1EventsByEventIdPhotoErrors];

export type PatchApiV1EventsByEventIdPhotoResponses = {
    /**
     * Success
     */
    200: EventShortEntry;
};

export type PatchApiV1EventsByEventIdPhotoResponse = PatchApiV1EventsByEventIdPhotoResponses[keyof PatchApiV1EventsByEventIdPhotoResponses];

export type PostApiV1EventsByEventIdCompleteData = {
    body?: never;
    path: {
        eventId: string;
    };
    query?: never;
    url: '/api/v1/events/{eventId}/complete';
};

export type PostApiV1EventsByEventIdCompleteErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
};

export type PostApiV1EventsByEventIdCompleteError = PostApiV1EventsByEventIdCompleteErrors[keyof PostApiV1EventsByEventIdCompleteErrors];

export type PostApiV1EventsByEventIdCompleteResponses = {
    /**
     * Success
     */
    200: EventShortEntry;
};

export type PostApiV1EventsByEventIdCompleteResponse = PostApiV1EventsByEventIdCompleteResponses[keyof PostApiV1EventsByEventIdCompleteResponses];

export type PostApiV1EventsByEventIdReopenData = {
    body?: never;
    path: {
        eventId: string;
    };
    query?: never;
    url: '/api/v1/events/{eventId}/reopen';
};

export type PostApiV1EventsByEventIdReopenErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
};

export type PostApiV1EventsByEventIdReopenError = PostApiV1EventsByEventIdReopenErrors[keyof PostApiV1EventsByEventIdReopenErrors];

export type PostApiV1EventsByEventIdReopenResponses = {
    /**
     * Success
     */
    200: EventShortEntry;
};

export type PostApiV1EventsByEventIdReopenResponse = PostApiV1EventsByEventIdReopenResponses[keyof PostApiV1EventsByEventIdReopenResponses];

export type PostApiV1EventsByEventIdCheckoutData = {
    body?: never;
    path: {
        eventId: string;
    };
    query?: never;
    url: '/api/v1/events/{eventId}/checkout';
};

export type PostApiV1EventsByEventIdCheckoutErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
};

export type PostApiV1EventsByEventIdCheckoutError = PostApiV1EventsByEventIdCheckoutErrors[keyof PostApiV1EventsByEventIdCheckoutErrors];

export type PostApiV1EventsByEventIdMediaFormFileData = {
    body?: {
        File?: Blob | File;
        MediaType: MediaType;
        Link?: string;
    };
    path: {
        eventId: string;
    };
    query?: never;
    url: '/api/v1/events/{eventId}/media/form-file';
};

export type PostApiV1EventsByEventIdMediaFormFileErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Client Error
     */
    415: ApiError;
};

export type PostApiV1EventsByEventIdMediaFormFileError = PostApiV1EventsByEventIdMediaFormFileErrors[keyof PostApiV1EventsByEventIdMediaFormFileErrors];

export type PostApiV1EventsByEventIdMediaFormFileResponses = {
    /**
     * Success
     */
    200: MediaShortEntry;
};

export type PostApiV1EventsByEventIdMediaFormFileResponse = PostApiV1EventsByEventIdMediaFormFileResponses[keyof PostApiV1EventsByEventIdMediaFormFileResponses];

export type GetApiV1EventsByEventIdMediaByMediaIdFormFileData = {
    body?: never;
    path: {
        eventId: string;
        mediaId: string;
    };
    query?: never;
    url: '/api/v1/events/{eventId}/media/{mediaId}/form-file';
};

export type GetApiV1EventsByEventIdMediaByMediaIdFormFileErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
};

export type GetApiV1EventsByEventIdMediaByMediaIdFormFileError = GetApiV1EventsByEventIdMediaByMediaIdFormFileErrors[keyof GetApiV1EventsByEventIdMediaByMediaIdFormFileErrors];

export type GetApiV1EventsByEventIdMediaByMediaIdFormFileResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiV1EventsByEventIdMediaByMediaIdMetadataData = {
    body?: never;
    path: {
        eventId: string;
        mediaId: string;
    };
    query?: never;
    url: '/api/v1/events/{eventId}/media/{mediaId}/metadata';
};

export type GetApiV1EventsByEventIdMediaByMediaIdMetadataErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
};

export type GetApiV1EventsByEventIdMediaByMediaIdMetadataError = GetApiV1EventsByEventIdMediaByMediaIdMetadataErrors[keyof GetApiV1EventsByEventIdMediaByMediaIdMetadataErrors];

export type GetApiV1EventsByEventIdMediaByMediaIdMetadataResponses = {
    /**
     * Success
     */
    200: GetMediaEntry;
};

export type GetApiV1EventsByEventIdMediaByMediaIdMetadataResponse = GetApiV1EventsByEventIdMediaByMediaIdMetadataResponses[keyof GetApiV1EventsByEventIdMediaByMediaIdMetadataResponses];

export type DeleteApiV1EventsByEventIdMediaByMediaIdData = {
    body?: never;
    path: {
        eventId: string;
        mediaId: string;
    };
    query?: never;
    url: '/api/v1/events/{eventId}/media/{mediaId}';
};

export type DeleteApiV1EventsByEventIdMediaByMediaIdErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
};

export type DeleteApiV1EventsByEventIdMediaByMediaIdError = DeleteApiV1EventsByEventIdMediaByMediaIdErrors[keyof DeleteApiV1EventsByEventIdMediaByMediaIdErrors];

export type DeleteApiV1EventsByEventIdMediaByMediaIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiV1EventsByEventIdMediaMetadataData = {
    body?: never;
    path: {
        eventId: string;
    };
    query?: {
        offset?: number;
        limit?: number;
        createdDateStart?: string;
        createdDateEnd?: string;
        mediaType?: MediaType;
    };
    url: '/api/v1/events/{eventId}/media/metadata';
};

export type GetApiV1EventsByEventIdMediaMetadataErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
};

export type GetApiV1EventsByEventIdMediaMetadataError = GetApiV1EventsByEventIdMediaMetadataErrors[keyof GetApiV1EventsByEventIdMediaMetadataErrors];

export type GetApiV1EventsByEventIdMediaMetadataResponses = {
    /**
     * Success
     */
    200: Array<MediaShortEntry>;
};

export type GetApiV1EventsByEventIdMediaMetadataResponse = GetApiV1EventsByEventIdMediaMetadataResponses[keyof GetApiV1EventsByEventIdMediaMetadataResponses];

export type GetApiV1EventsByEventIdParticipantsData = {
    body?: never;
    path: {
        eventId: string;
    };
    query?: {
        offset?: number;
        limit?: number;
        userId?: string;
    };
    url: '/api/v1/events/{eventId}/participants';
};

export type GetApiV1EventsByEventIdParticipantsErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ApiError;
};

export type GetApiV1EventsByEventIdParticipantsError = GetApiV1EventsByEventIdParticipantsErrors[keyof GetApiV1EventsByEventIdParticipantsErrors];

export type GetApiV1EventsByEventIdParticipantsResponses = {
    /**
     * Success
     */
    200: ParticipantShortEntryResponse;
};

export type GetApiV1EventsByEventIdParticipantsResponse = GetApiV1EventsByEventIdParticipantsResponses[keyof GetApiV1EventsByEventIdParticipantsResponses];

export type PostApiV1EventsByEventIdParticipantsData = {
    body?: UpsertParticipantEntry;
    path: {
        eventId: string;
    };
    query?: never;
    url: '/api/v1/events/{eventId}/participants';
};

export type PostApiV1EventsByEventIdParticipantsErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
};

export type PostApiV1EventsByEventIdParticipantsError = PostApiV1EventsByEventIdParticipantsErrors[keyof PostApiV1EventsByEventIdParticipantsErrors];

export type PostApiV1EventsByEventIdParticipantsResponses = {
    /**
     * Success
     */
    200: ParticipantShortEntry;
};

export type PostApiV1EventsByEventIdParticipantsResponse = PostApiV1EventsByEventIdParticipantsResponses[keyof PostApiV1EventsByEventIdParticipantsResponses];

export type DeleteApiV1EventsByEventIdParticipantsByParticipantIdData = {
    body?: never;
    path: {
        eventId: string;
        participantId: string;
    };
    query?: never;
    url: '/api/v1/events/{eventId}/participants/{participantId}';
};

export type DeleteApiV1EventsByEventIdParticipantsByParticipantIdErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
};

export type DeleteApiV1EventsByEventIdParticipantsByParticipantIdError = DeleteApiV1EventsByEventIdParticipantsByParticipantIdErrors[keyof DeleteApiV1EventsByEventIdParticipantsByParticipantIdErrors];

export type DeleteApiV1EventsByEventIdParticipantsByParticipantIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiV1EventsByEventIdParticipantsByParticipantIdData = {
    body?: never;
    path: {
        eventId: string;
        participantId: string;
    };
    query?: never;
    url: '/api/v1/events/{eventId}/participants/{participantId}';
};

export type GetApiV1EventsByEventIdParticipantsByParticipantIdErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ApiError;
};

export type GetApiV1EventsByEventIdParticipantsByParticipantIdError = GetApiV1EventsByEventIdParticipantsByParticipantIdErrors[keyof GetApiV1EventsByEventIdParticipantsByParticipantIdErrors];

export type GetApiV1EventsByEventIdParticipantsByParticipantIdResponses = {
    /**
     * Success
     */
    200: GetParticipantEntry;
};

export type GetApiV1EventsByEventIdParticipantsByParticipantIdResponse = GetApiV1EventsByEventIdParticipantsByParticipantIdResponses[keyof GetApiV1EventsByEventIdParticipantsByParticipantIdResponses];

export type GetApiV1EventsByEventIdPurchasesData = {
    body?: never;
    path: {
        eventId: string;
    };
    query?: {
        offset?: number;
        limit?: number;
        name?: string;
        costMin?: number;
        costMax?: number;
        isComplete?: boolean;
        purchaseIds?: Array<string>;
    };
    url: '/api/v1/events/{eventId}/purchases';
};

export type GetApiV1EventsByEventIdPurchasesErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ApiError;
};

export type GetApiV1EventsByEventIdPurchasesError = GetApiV1EventsByEventIdPurchasesErrors[keyof GetApiV1EventsByEventIdPurchasesErrors];

export type GetApiV1EventsByEventIdPurchasesResponses = {
    /**
     * Success
     */
    200: GetPurchaseEntryResponse;
};

export type GetApiV1EventsByEventIdPurchasesResponse = GetApiV1EventsByEventIdPurchasesResponses[keyof GetApiV1EventsByEventIdPurchasesResponses];

export type PostApiV1EventsByEventIdPurchasesData = {
    body?: AddPurchaseEntry;
    path: {
        eventId: string;
    };
    query?: never;
    url: '/api/v1/events/{eventId}/purchases';
};

export type PostApiV1EventsByEventIdPurchasesErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
};

export type PostApiV1EventsByEventIdPurchasesError = PostApiV1EventsByEventIdPurchasesErrors[keyof PostApiV1EventsByEventIdPurchasesErrors];

export type PostApiV1EventsByEventIdPurchasesResponses = {
    /**
     * Success
     */
    200: PurchaseShortEntry;
};

export type PostApiV1EventsByEventIdPurchasesResponse = PostApiV1EventsByEventIdPurchasesResponses[keyof PostApiV1EventsByEventIdPurchasesResponses];

export type DeleteApiV1EventsByEventIdPurchasesByPurchaseIdData = {
    body?: never;
    path: {
        eventId: string;
        purchaseId: string;
    };
    query?: never;
    url: '/api/v1/events/{eventId}/purchases/{purchaseId}';
};

export type DeleteApiV1EventsByEventIdPurchasesByPurchaseIdErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
};

export type DeleteApiV1EventsByEventIdPurchasesByPurchaseIdError = DeleteApiV1EventsByEventIdPurchasesByPurchaseIdErrors[keyof DeleteApiV1EventsByEventIdPurchasesByPurchaseIdErrors];

export type DeleteApiV1EventsByEventIdPurchasesByPurchaseIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiV1EventsByEventIdPurchasesByPurchaseIdData = {
    body?: never;
    path: {
        eventId: string;
        purchaseId: string;
    };
    query?: never;
    url: '/api/v1/events/{eventId}/purchases/{purchaseId}';
};

export type GetApiV1EventsByEventIdPurchasesByPurchaseIdErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ApiError;
};

export type GetApiV1EventsByEventIdPurchasesByPurchaseIdError = GetApiV1EventsByEventIdPurchasesByPurchaseIdErrors[keyof GetApiV1EventsByEventIdPurchasesByPurchaseIdErrors];

export type GetApiV1EventsByEventIdPurchasesByPurchaseIdResponses = {
    /**
     * Success
     */
    200: GetPurchaseEntry;
};

export type GetApiV1EventsByEventIdPurchasesByPurchaseIdResponse = GetApiV1EventsByEventIdPurchasesByPurchaseIdResponses[keyof GetApiV1EventsByEventIdPurchasesByPurchaseIdResponses];

export type PatchApiV1EventsByEventIdPurchasesByPurchaseIdData = {
    body?: UpdatePurchaseEntry;
    path: {
        eventId: string;
        purchaseId: string;
    };
    query?: never;
    url: '/api/v1/events/{eventId}/purchases/{purchaseId}';
};

export type PatchApiV1EventsByEventIdPurchasesByPurchaseIdErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
};

export type PatchApiV1EventsByEventIdPurchasesByPurchaseIdError = PatchApiV1EventsByEventIdPurchasesByPurchaseIdErrors[keyof PatchApiV1EventsByEventIdPurchasesByPurchaseIdErrors];

export type PatchApiV1EventsByEventIdPurchasesByPurchaseIdResponses = {
    /**
     * Success
     */
    200: PurchaseShortEntry;
};

export type PatchApiV1EventsByEventIdPurchasesByPurchaseIdResponse = PatchApiV1EventsByEventIdPurchasesByPurchaseIdResponses[keyof PatchApiV1EventsByEventIdPurchasesByPurchaseIdResponses];
